import { PageShell, SectionIntro } from "@/components/site-chrome";

type LegalPageProps = {
  kind: "privacy" | "terms";
};

const privacySections = [
  ["Information we collect", "GrowthAgent AI may process account details, workspace configuration, lead records, outreach content, campaign activity, reply metadata, analytics events, and support messages provided by customers or generated by the platform."],
  ["How we use information", "We use information to operate the product, research and enrich leads, generate outreach drafts, track replies, prevent abuse, improve reliability, provide support, and maintain audit logs."],
  ["Customer data", "Customers are responsible for the data they import, connect, or instruct GrowthAgent AI to process. We treat customer CRM, lead, message, and campaign data as confidential workspace data."],
  ["AI processing", "AI systems may be used to summarize company context, draft outreach, classify replies, recommend follow-ups, and surface risks. Human review controls can be enabled before outbound messages are sent."],
  ["Security", "We use access controls, rate limits, audit logging, secret management, encrypted transport, and least-privilege database policies to reduce risk. No system can be guaranteed completely secure."],
  ["Data retention", "Workspace data is retained while an account is active unless deleted by the customer or required for security, legal, billing, or compliance reasons."],
  ["Contact", "For privacy requests, security concerns, or data questions, contact the GrowthAgent AI team through the demo/contact form."],
];

const termsSections = [
  ["Use of the service", "GrowthAgent AI provides software for lead research, outreach preparation, email automation, reply tracking, follow-up planning, CRM operations, and sales analytics."],
  ["Responsible outbound", "Customers must use the service lawfully, respect opt-outs, avoid spam, honor platform rules, and ensure they have a valid basis to contact prospects."],
  ["Customer responsibilities", "Customers are responsible for their connected accounts, imported data, outreach instructions, compliance settings, domain reputation, and messages approved or sent through the platform."],
  ["Automation limits", "GrowthAgent AI can assist with autonomous workflows, but customers should configure safety limits, review sensitive actions, and monitor results. The product does not guarantee sales, meetings, replies, or revenue."],
  ["Acceptable use", "The service may not be used for phishing, credential theft, harassment, illegal scraping, malware, deceptive impersonation, or sending prohibited content."],
  ["Availability", "We aim to provide a reliable service, but availability may be affected by maintenance, providers, connected APIs, rate limits, third-party outages, or customer configuration issues."],
  ["Changes", "These terms may be updated as the product evolves. Continued use of the service means acceptance of the updated terms."],
];

export function LegalPage({ kind }: LegalPageProps) {
  const isPrivacy = kind === "privacy";
  const sections = isPrivacy ? privacySections : termsSections;

  return (
    <PageShell>
      <main className="px-5 py-20 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl">
          <SectionIntro
            align="left"
            eyebrow="Legal"
            title={isPrivacy ? "Privacy Policy" : "Terms of Service"}
            text={
              isPrivacy
                ? "How GrowthAgent AI handles customer data, lead records, outreach content, and platform activity."
                : "The basic rules for using GrowthAgent AI responsibly as a sales automation platform."
            }
          />
          <div className="mt-10 rounded-[2rem] border border-white/10 bg-white/[0.06] p-6 shadow-[0_24px_80px_rgba(0,0,0,0.28)] backdrop-blur-xl sm:p-8">
            <p className="text-sm font-semibold text-slate-400">Last updated: June 18, 2026</p>
            <div className="mt-8 space-y-7">
              {sections.map(([title, body]) => (
                <section key={title} className="border-t border-white/10 pt-7 first:border-t-0 first:pt-0">
                  <h2 className="text-xl font-black text-white">{title}</h2>
                  <p className="mt-3 text-base leading-7 text-slate-300">{body}</p>
                </section>
              ))}
            </div>
            <p className="mt-10 rounded-2xl border border-[#ffcb00]/25 bg-[#ffcb00]/10 p-4 text-sm leading-6 text-[#ffe58a]">
              This page is a product-ready starting point, not legal advice. Before selling to companies, have a qualified lawyer review the final policy, terms, DPA, and outbound compliance language.
            </p>
          </div>
        </div>
      </main>
    </PageShell>
  );
}
